### ISSUE TITLE
tsickle produces wrong module references when using baseUrl and outDir simultaneously.

### ISSUE THREAD

**Issue by rubenlg** [angular/tsickle#490]
Directory structure:
```
.
├── lib
│   └── module.ts
└── program
    ├── main.ts
    └── tsconfig.json
```

lib/module.ts:
```typescript
export function foo() {
  console.log('foo');
}
```

program/main.ts:
```typescript
import {foo} from 'lib/module';

function main() {
  foo();
}
```

program/tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "baseUrl": "../",
    "outDir": "jsout"
  }
}
```

**Expected**: 
The resulting code can be compiled with closure compiler.

**Actual**:
```sh
jsout/program/main.js:3: ERROR - Required namespace "lib.module" never defined.
```
Here are the `module` names generated in the two files:

jsout/lib/module.js:
```javascript
goog.module('jsout.lib.module');
```

jsout/program/main.js:
```
goog.module('jsout.program.main'); // ...
var module_1 = goog.require('lib.module');
```

The name of the `module` module should be the same in both cases.

**NOTE**: The bug still reproduces if `lib` is under `program` and `baseUrl` is ".". I just thought that it was a more realistic case to have libraries outside of your program, perhaps shared with other programs and libraries.

**Comment by rubenlg** [comment]
Note that the original bug listed above is now fixed, but it has reincarnated in a slightly different form, now it affects goog.forwardDeclare instead of goog.require.

**Comment by rubenlg** [comment]
FYI: I created the following test case that reproduces the outstanding issue:
https://github.com/rubenlg/tsickle/commit/f57f03ba94cb7f286572359e9ff343d24b46b941

You can see what happens by running:
```sh
bazel test test:paths_test
```

(If you apply that commit as a patch on the original tsickle, you also need to drop an unused import)

I haven't looked very deeply into the tsickle codebase to figure out what's the right fix. My initial reaction would be to always generate module names from the absolute file paths, but that might break other things. Any guidance would be appreciated.

**Comment by rubenlg** [comment]
I forked tsickle yesterday (April 2) evening, with the GitHub UI, which I assume forks from master.

**Comment by mprobst** [comment]
Then I guess the problem can still happen in some call path, or the rootDir fix should be amended by considering baseUrl in some context.

**Comment by mprobst** [comment]
For reference, the fix I mentioned was a2213f85a20a596e10bfc5066169eadda1c58096.

**Comment by rubenlg** [comment]
In the test case above, I think what's confusing tsickle now is the usage of `paths` to create aliases (like what's typically done to get `@angular` to work on imports). tsickle seems to use the raw import to construct the require statements without resolving the alias first, and then the `goog.require` doesn't match the `goog.module`.

`"baseUrl": "../"` is still failing with the released version of tsickle, but perhaps it's solved in HEAD. Is there an easy way to run tsickle on HEAD? I couldn't find any bazel command to do that in the README.md instructions. Or do I need to create a node module and look in bin/?

If I can test the other cases in HEAD and verify that now the only problem is `paths`, I'll be happy to close this issue and file a separate one.

**Comment by mprobst** [comment]
I think you should be able to change the WORKSPACE to refer to a head
version of tsickle. @alexeagle will know exactly how to.

**Comment by alexeagle** [comment]
the `ts_library` rule should pick up dependencies (including tsickle) from your `node_modules` so you just need to install the latest version following the usual npm methods (npm link, npm install, etc)

**Comment by rubenlg** [comment]
I just tried the version from head and it still fails with the example in the first post of the thread.

In one JS file I have:
```typescript
goog.module('jsout.lib.module')
```

In another JS file I have:
```typescript
var module_1 = goog.require('lib.module');
```

Exactly the same error as before. It seems to fail for cross-directory dependencies (e.g. from program to lib in the example above) and also in cases annotated with `// force type-only module to be loaded`

**Comment by rubenlg** [comment]
FYI: I tried again with 0.34.3, and now tsickle detects its internal inconsistencies, as it fails in the following places:
```
AssertionError [ERR_ASSERTION]: expected "../../foo/bar/baz.ts" to be absolute
    at Object.assertAbsolute (/.../node_modules/tsickle/src/cli_support.js:28:9)
    at Object.emitWithTsickle (/.../node_modules/tsickle/src/tsickle.js:98:31)
```
and
```
AssertionError [ERR_ASSERTION]: expected "foo/bar/baz.js" to be absolute
    at Object.assertAbsolute (/.../node_modules/tsickle/src/cli_support.js:28:9)
    at Object.writeFileImpl [as writeFile] (/.../node_modules/tsickle/src/tsickle.js:140:27)
```

However, that means I can't even run it in my projects, because it doesn't output anything. Before that change, I could run it and then do a pass to fix all the module references with a script. Now I have to drop these checks to be able to make progress.

Potentially related to #930.
